// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqRFMO-096QuPH2zlaTGni35lSj1ccZXY',
    appId: '1:196121146264:web:77c19b3ad99fce3829f1ed',
    messagingSenderId: '196121146264',
    projectId: 'winatra',
    authDomain: 'winatra.firebaseapp.com',
    storageBucket: 'winatra.firebasestorage.app',
    measurementId: 'G-DMWK0C9MT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6fKCsrodqGyKbU9Mej-U08nyFeDxqdE8',
    appId: '1:196121146264:android:ecfeef6458edd7cb29f1ed',
    messagingSenderId: '196121146264',
    projectId: 'winatra',
    storageBucket: 'winatra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWj-vYtFWiNXRFLbv5Gy2e4cwb_H7J5C4',
    appId: '1:196121146264:ios:2261a84d341397f529f1ed',
    messagingSenderId: '196121146264',
    projectId: 'winatra',
    storageBucket: 'winatra.firebasestorage.app',
    iosBundleId: 'com.example.winatraai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWj-vYtFWiNXRFLbv5Gy2e4cwb_H7J5C4',
    appId: '1:196121146264:ios:2261a84d341397f529f1ed',
    messagingSenderId: '196121146264',
    projectId: 'winatra',
    storageBucket: 'winatra.firebasestorage.app',
    iosBundleId: 'com.example.winatraai',
  );
}
